[package]
name = "blaze_launchpad"
version = "1.0.0"
authors = []

[addresses]
blaze_token_launchpad = "0x9239ac2bb7bb998c6d19d1b309dd2093f130185710415832caf30bf0c99d678a"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]
